-- BL-O-Meter: BL II/2026 Import + BL User Accounts
-- Generiert am 2026-04-16

-- === BL USER ACCOUNTS (PIN: 1929) ===
INSERT INTO users (email, name, pin_hash, role) VALUES ('alexandra.klaus@dpsg.de', 'Alexandra Klaus', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Alexandra Klaus', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('annkathrin.meyer@dpsg.de', 'Annkathrin Meyer', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Annkathrin Meyer', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('baerbel.thomas@dpsg.de', 'Bärbel Thomas', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Bärbel Thomas', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('bettina.koss@dpsg.de', 'Bettina Koß', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Bettina Koß', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('c-m.zaremba@web.de', 'Cara-Milena Zaremba', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Cara-Milena Zaremba', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('cara-milena.zaremba@dpsg.de', 'Cara-Milena Zaremba', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Cara-Milena Zaremba', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('charbel.bechara@dpsg.de', 'Charbel Bechara', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Charbel Bechara', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('eva.kopic@dpsg.de', 'Eva Kopic', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Eva Kopic', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('frankamarie.bernreiter@dpsg.de', 'Franka Marie Bernreiter', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Franka Marie Bernreiter', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('hannah.rieger@dpsg.de', 'Hannah Rieger', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Hannah Rieger', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('isabella.braun@dpsg.de', 'Isabella Braun', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Isabella Braun', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('jan.fligge@dpsg.de', 'Jan Fligge', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Jan Fligge', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('jana.huetten@dpsg.de', 'Jana Huetten', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Jana Huetten', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('janine.zensen@dpsg.de', 'Janine Zensen', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Janine Zensen', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('joerg.vater@dpsg.de', 'Joerg Vater', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Joerg Vater', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('karl.r.thiel@dpsg.de', 'Karl R. Thiel', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Karl R. Thiel', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('katharina.scholl@dpsg.de', 'Katharina Scholl', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Katharina Scholl', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('kristof.moersch@dpsg.de', 'Kristof Moersch', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Kristof Moersch', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('lea.voigtlaender@dpsg.de', 'Lea Voigtlaender', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Lea Voigtlaender', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('lena.schmitz@dpsg.de', 'Lena Schmitz', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Lena Schmitz', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('leonie.silkenbeumer@dpsg.de', 'Leonie Silkenbeumer', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Leonie Silkenbeumer', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('lukas.haurand@dpsg.de', 'Lukas Haurand', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Lukas Haurand', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('lukas.matzick@dpsg.de', 'Lukas Matzick', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Lukas Matzick', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('manuel.ganser@dpsg.de', 'Manuel Ganser', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Manuel Ganser', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('marius.ducke@dpsg.de', 'Marius Ducke', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Marius Ducke', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('maximilian.strozyk@dpsg.de', 'Maximilian Strozyk', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Maximilian Strozyk', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('michael.wenzel@dpsg.de', 'Michael Wenzel', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Michael Wenzel', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('miriam.noske@dpsg.de', 'Miriam Noske', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Miriam Noske', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('nuralhuda.kurt@dpsg.de', 'Nuralhuda Kurt', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Nuralhuda Kurt', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('pierre.schmitt@dpsg.de', 'Pierre Schmitt', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Pierre Schmitt', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('ricarda.koch@dpsg.de', 'Ricarda Koch', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Ricarda Koch', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('sandra.leusch@dpsg.de', 'Sandra Leusch', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Sandra Leusch', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('sandra.zimmermann@dpsg.de', 'Sandra Zimmermann', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Sandra Zimmermann', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('sebastian.becker@dpsg.de', 'Sebastian Becker', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Sebastian Becker', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('sebastian.jansen@dpsg.de', 'Sebastian Jansen', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Sebastian Jansen', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('sebastian.paeffgen@dpsg.de', 'Sebastian Päffgen', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Sebastian Päffgen', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('sina.spinczyk@dpsg.de', 'Sina Spinczyk', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Sina Spinczyk', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';
INSERT INTO users (email, name, pin_hash, role) VALUES ('venka.koglin@dpsg.de', 'Venka Koglin', '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', 'BL') ON CONFLICT (email) DO UPDATE SET name = 'Venka Koglin', pin_hash = '$2a$12$J98ChIjkL/PdCBAYTWOVguXUKhFzow33zOj1CVFxJx/DFkLh5vei2', role = 'BL';

-- === BL II/2026 IMPORT ===
INSERT INTO surveys (title, subtitle, survey_date, template_id, status, zusammenarbeit_items, numeric_items, freitext_items, closed_at, category)
VALUES ('BL II/2026', 'Bundesleitung April 2026 Westernohe', '2026-04-11', 1, 'closed',
  (SELECT zusammenarbeit_items FROM templates WHERE is_default = true),
  (SELECT numeric_items FROM templates WHERE is_default = true),
  (SELECT freitext_items FROM templates WHERE is_default = true),
  NOW(), 'BL');

INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Strategie', 0);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Mitarbeit auf Bundesebene I-V', 1);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Jahresaktion', 2);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Umsetzung Reduktion CO2 Emissionen', 3);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'BV 2026', 4);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Aufarbeitung', 5);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Kandiat*innen-Vorstellung #1 & #2', 6);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Politischer Kompaß', 7);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Ausbildung', 8);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Austausch mit Stufen- und Fachdelegierten', 9);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Austausch BuVo & ea. BL', 10);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'PIW2026', 11);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Sonstiges & Themenspeicher', 12);
INSERT INTO survey_agenda_items (survey_id, label, sort_order) VALUES (currval('surveys_id_seq'), 'Feedback', 13);

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 8);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 5);
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'gelungen', 'Politischer Kompass');
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'themen', 'Pol. Kompass, Strategie, Aufarbeitung');

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 7);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 8);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 4);
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'gelungen', 'Rahmen');
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'themen', 'BV, Aufarbeitung, PiW');

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 7);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 8);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 3);

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 4);
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'gelungen', 'Der Einstieg zum Feedback, das Rahmenprogramm, eigentlich waren alle gut');
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'themen', 'Aufarbeitung, BV, Ausbildung');
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'sonstiges', 'Danke für die abwechslungsreichen TO und die gute Stimmung');

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 7);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 3);
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'gelungen', 'Politische Bildung KG Arbeit war hektisch aber gut und wichtig, Check-ins (Mitarbeit auf Bundesebene) waren super');
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'themen', 'Alkohol im Verband, Kandidaturen BuVo, Strategie');
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'sonstiges', 'Reflexionen digital sind angesichts unseres Zeitplans zwar super, allerdings finde ich auch eine kurze Reflexion zu "was fand ich dieses Wochenende besonders gut, was hat mich gestört?" auch wichtig');

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 8);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 3);

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 6);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 5);
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'themen', 'Strategie, Aufarbeitung, Ausbildung');

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 8);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 8);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 5);

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 7);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 8);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 4);

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 8);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 4);
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'gelungen', 'BV');
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'themen', 'BV, Aufarbeitung, Strategie');
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'sonstiges', 'Es war gefühlt nicht ganz so vollgepackt und stressig wie andere BL-Sitzungen schonmal waren');

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 1);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 7);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 1);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 2);

INSERT INTO responses (survey_id) VALUES (currval('surveys_id_seq'));
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 0), 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 1), 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 2), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 3), 2);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 4), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 5), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 6), 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 7), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 8), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 9), 3);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 10), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 11), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 12), 0);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'agenda', (SELECT id::text FROM survey_agenda_items WHERE survey_id = currval('surveys_id_seq') AND sort_order = 13), 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '0', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '1', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '2', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '3', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '4', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '5', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '6', 5);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'zusammenarbeit', '7', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'strategisch', 7);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'operativ', 7);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'mehrwert', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'entwicklung', 4);
INSERT INTO response_answers (response_id, section, question_key, value_numeric) VALUES (currval('responses_id_seq'), 'numeric', 'belastung', 5);
INSERT INTO response_answers (response_id, section, question_key, value_text) VALUES (currval('responses_id_seq'), 'freitext', 'themen', 'Aufarbeitung, Strategie, Ausbildung');

-- Total: 12 responses, 38 users